### ISSUE TITLE
转发动态推送类型被排除

### ISSUE THREAD

**Issue by ArthurCui430** [nfe-w/bili_dynamic_push#1]
query_bili.py中
`if dynamic_type not in [2, 4, 8, 64]:`

应该把1也排出？否则转发动态不会被推送。

nga那边不能回复，来git提个issue

**Comment by nfe-w** [comment]
不好意思，一直没注意到issue

因为之前有很多小伙伴反馈，「转发动态」的提醒频率过高（例如批量转发二创），短时间内会有大量推送

然后简单的投了一下票，将「转发动态」的提醒移除掉了
https://github.com/yr-wan/bili_dynamic_push/commit/c82eadd5cd9fd124288b5e2fb3b0ea473874c0b9
