### ISSUE TITLE
KeyError: 'cards'`

### ISSUE THREAD

**Issue by BestLemoon** [nfe-w/bili_dynamic_push#4]
每次运行一段时间就会报错，用的是Docker运行，报错信息如下
`Traceback (most recent call last):
  File "/app/main.py", line 35, in <module>
    query_dynamic(_)
  File "/app/query_bili.py", line 37, in query_dynamic
    if len(data['cards']) == 0:
KeyError: 'cards'`

**Comment by nfe-w** [comment]
请求频率设置的是多少呢，可能是频率太高被b站ban了

**Comment by BestLemoon** [comment]
30，原来设置的60可以稳定运行吗？

**Comment by nfe-w** [comment]
我看了下我的配置，我是5分钟内累计请求30次，一直是稳定运行的，如果你那边改久一点还是不能请求的话我加些异常处理

**Comment by BigBlueBaby** [comment]
> 我看了下我的配置，我是5分钟内累计请求30次，一直是稳定运行的，如果你那边改久一点还是不能请求的话我加些异常处理

我也是遇到这个错误导致推送程序报错了，运行了20天报错的，我先自己加了异常处理，应该不会直接停止运行了

**Comment by nfe-w** [comment]
> > 我看了下我的配置，我是5分钟内累计请求30次，一直是稳定运行的，如果你那边改久一点还是不能请求的话我加些异常处理
> 
> 
> 
> 我也是遇到这个错误导致推送程序报错了，运行了20天报错的，我先自己加了异常处理，应该不会直接停止运行了

@BigBlueBaby 可以试试 [nfe-w/aio-dynamic-push](https://github.com/nfe-w/aio-dynamic-push) 对你说的这种情况增加了处理🥸

**Comment by BigBlueBaby** [comment]
> > > 我看了下我的配置，我是5分钟内累计请求30次，一直是稳定运行的，如果你那边改久一点还是不能请求的话我加些异常处理
> > 
> > 
> > 我也是遇到这个错误导致推送程序报错了，运行了20天报错的，我先自己加了异常处理，应该不会直接停止运行了
> 
> @BigBlueBaby 可以试试 [nfe-w/aio-dynamic-push](https://github.com/nfe-w/aio-dynamic-push) 对你说的这种情况增加了处理🥸

谢啦，我去试试
